project:
  type: book
    
execute:
  freeze: auto

book:
  title: "Manuel de protection des tableaux"
  author: "Clara Baudry, Arlindo Dos Santos, Julien Jamme, Nathanaël Rastout"
  date: last-modified
  date-format: iso
  
  chapters:
    - part: "Introduction"
      chapters: 
        - index.qmd
        - 01_notions.qmd
    - part: "La pose de secret"
      chapters: 
        - 02_secret_un_tableau.qmd
        - 03_analyser_une_demande.qmd
        - 04_secret_tableaux_lies.qmd
    - part: "En pratique"
      chapters: 
        - chapters/fiches_pratiques/introduction.qmd
        - chapters/fiches_pratiques/tabulate_micro_data.qmd
        - chapters/fiches_pratiques/var_hierarchique.qmd
        - chapters/fiches_pratiques/var_hierarchique_nonemboitee.qmd
        - chapters/fiches_pratiques/couts.qmd
        - 06_outils.qmd
    - part: "Annexes"
      chapters:
        - chapters/annexes/regles.qmd
        - chapters/annexes/manipuler_les_listes.qmd
  
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - custom.scss
    toc-depth: 5
    toc-title: Plan
    link-external-newwindow: true



