project:
  type: book
execute:
  freeze: auto

book:
  title: "Manuel de protection des tableaux"
  author: "Julien Jamme, Nathanaël Rastout"
  date: "03/04/2023"
  language: fr
  chapters:
    - index.qmd
    - 01_regles.qmd
    - 02_notions.qmd
    - 03_analyser_une_demande.qmd
    - 04_fiches_pratiques.qmd
    - 05_les_outils.qmd
    - 06_annexes.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



