project:
  type: book
execute:
  freeze: auto

book:
  title: "Manuel de protection des tableaux"
  author: "Julien Jamme, Nathanaël Rastout"
  date: "03/04/2023"
  chapters:
    - index.qmd
    - 01_notions.qmd
    - 02_secret_un_tableau.qmd
    - 03_analyser_une_demande.qmd
    - 04_secret_tableaux_lies.qmd
    - 05_fiches_pratiques.qmd
    - 06_expert.qmd
    - 07_annexes.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - custom.scss
    toc-depth: 5
  pdf:
    documentclass: scrreprt



